### PR TITLE
Add Heroku deploy button

### PR DESCRIPTION
**Pull request by chao-xian**
As discussed in https://github.com/slack-ruby/slack-ruby-bot/issues/60#issuecomment-242214213

### CODE REVIEW

**Comment by dblock** [comment]
Does putting `required: true` and no default value make the heroku deploy button prompt for that API token value? I feel like I've seen thats somewhere. This way none of the manual steps are needed.

**Comment by chao-xian** [comment]
I tried it out and it will pre-fill that config var with the current `UPDATE_WITH_YOUR_TOKEN` value:

screenshot

**Comment by chao-xian** [comment]
Actually as that's the case the instruction in the README is superfluous so I'll remove it.

**Comment by dblock** [comment]
I would remove the default "UPDATE_WITH_YOUR_TOKEN" value, and move that in the description. This way someone *has* to fill it.

**Comment by dblock** [comment]
The build is failing because of some dependency, just update the ruby version in travis to 2.3.1 or something.

**Comment by chao-xian** [comment]
Where do I set the ruby ver for Travis? I've not used it before (I usually Bamboo).

**Comment by dblock** [comment]
.travis.yml

**Comment by dblock** [comment]
Thanks, merging.

**Pull request merged**
